pipeline {
    agent any

    environment {
        APP_NAME = "pega-customer"
        VERSION = "1.0.0"
        JFROG_URL = "https://trialm3fa23.jfrog.io"
        ECR_REGISTRY = "775698064045.dkr.ecr.us-east-1.amazonaws.com"  
        ECR_REPO = "${ECR_REGISTRY}/${APP_NAME}"
        HELM_CHART = "./pega-helm"
        GITOPS_REPO = "~/deployment-workspace/pega-gitops"
    }

    stages {

        stage('Checkout SCM') {
            steps {
                git url: 'https://github.com/devkelzs/deployment-workspace.git', branch: 'main'
            }
        }

        stage('Download Artifact from JFrog') {
            steps {
                withCredentials([string(credentialsId: 'JFROG_TOKEN', variable: 'JFROG_TOKEN')]) {
                    sh '''
                        # Download the Pega artifact from JFrog
                        wget --header="Authorization: Bearer $JFROG_TOKEN" \
                             -O Customer_${VERSION}.zip \
                             ${JFROG_URL}/artifactory/pega-rules/Customer_010101_20260121T152131_GMT.zip
                    '''
                }
            }
        }

        stage('Unzip Artifact') {
            steps {
                sh '''
                    # Make sure docker folder exists
                    mkdir -p pega-docker

                    # Unzip the artifact into the docker build context
                    unzip -o Customer_${VERSION}.zip -d ./pega-docker/
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''echo "Building Docker image..."
                      docker build \
                        -t pega-customer:${VERSION} \
                        -f pega-ci/pega-docker/Dockerfile \
                         pega-ci/pega-docker

                '''
            }
        }

        stage('Push Image to ECR') {
            steps {
                withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                    sh '''
                        # Authenticate Docker to ECR
                        aws ecr get-login-password --region us-east-1 | \
                            docker login --username AWS --password-stdin ${ECR_REGISTRY}

                        # Tag and push image
                        docker tag ${APP_NAME}:${VERSION} ${ECR_REPO}:${VERSION}
                        docker push ${ECR_REPO}:${VERSION}
                    '''
                }
            }
        }

        stage('Helm Deploy') {
            steps {
                sh '''
                    # Create namespace if it doesn't exist
                    kubectl create namespace pega || true

                    # Deploy using Helm chart
                    helm upgrade --install ${APP_NAME} ${HELM_CHART} \
                        --namespace pega \
                        --set image.tag=${VERSION}
                '''
            }
        }

    }

    post {
        success {
            echo "✅ Pipeline completed successfully!"
        }
        failure {
            echo "❌ Pipeline failed — check the logs and fix errors."
        }
    }
}
